# Experiment 1: Classify with `dataset_style.json`

In [2]:
#imports
import warnings
warnings.filterwarnings('ignore')

import sys
sys.path.append('/home/elenaruiz/Documents/FNC')
import pandas as pd
import numpy as np
from src.utils import io
from src.fake_news_detector.core.classificators import LDA, QDA

## Import style dataset

In [3]:
articles = io.read_json_file('/home/elenaruiz/Documents/FNC/src/data/dataset_style.json')
df = pd.DataFrame(data=articles['articles'])

## Variables to classify

In [6]:
df_two = df[['mean_words_per_sentence', 'pert_total_nouns', 'n_words', 'title_n_words', 'title_sentiment' ]]
df_two['fake'] = df['fake']*1

In [7]:
df_two.head()

mean_words_per_sentence  pert_total_nouns  n_words  title_n_words  \
0                 4.521569          0.356863      255             10   
1                 4.840456          0.321937      351             12   
2                 4.285106          0.310638      235             14   
3                 4.120000          0.272000      125             12   
4                 4.536232          0.311594      138             12   

   title_sentiment  fake  
0          -0.5719     1  
1          -0.1027     1  
2          -0.4588     1  
3          -0.6202     1  
4          -0.4767     1

## Split datasets

In [11]:
# TODO SPLIT DF
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df_two, test_size=0.2, random_state=42)
df_train.head()

mean_words_per_sentence  pert_total_nouns  n_words  title_n_words  \
89                 4.811947          0.318584      452              6   
26                 4.624390          0.290244      410              8   
42                 4.601695          0.266949      236             10   
70                 5.162651          0.379518      166             13   
15                 4.262570          0.310056      358              9   

    title_sentiment  fake  
89           0.0000     0  
26          -0.7845     1  
42          -0.1027     1  
70          -0.1280     0  
15          -0.6908     1

In [12]:
def do_test(model,df_train, df_test, labels_x, label_tag, scaler, type_m):
    print('For labels:', ', '.join(labels_x))
    if type_m == 'LDA':
        pred = LDA.run_performance(model,  df_train[labels_x], df_train[label_tag], df_test[labels_x], df_test[label_tag], scaler)
    else:
        pred = QDA.run_performance(model,  df_train[labels_x], df_train[label_tag], df_test[labels_x], df_test[label_tag], scaler)
    return pred
        
results = {}

### LDA

In [13]:
n_components = 1
scaler = True
lda_model = LDA.create_LDA_model(n_components) # Create
labels_x = ['pert_total_nouns', 'n_words',  'title_sentiment']
res = do_test(lda_model, df_train, df_test,labels_x, 'fake', scaler, 'LDA')

For labels: pert_total_nouns, n_words, title_sentiment
Confusion matrix:
[[ 6  2]
 [ 2 11]]
REPORT:
              precision    recall  f1-score   support

           0       0.75      0.75      0.75         8
           1       0.85      0.85      0.85        13

   micro avg       0.81      0.81      0.81        21
   macro avg       0.80      0.80      0.80        21
weighted avg       0.81      0.81      0.81        21

Train precision score: 0.75
Test precision score: 0.8461538461538461


In [15]:
labels_x = ['pert_total_nouns','n_words', 'title_sentiment', 'title_n_words', 'mean_words_per_sentence']
res = do_test(lda_model, df_train, df_test,labels_x, 'fake', scaler, 'LDA')

For labels: pert_total_nouns, n_words, title_sentiment, title_n_words, mean_words_per_sentence
Confusion matrix:
[[ 5  3]
 [ 2 11]]
REPORT:
              precision    recall  f1-score   support

           0       0.71      0.62      0.67         8
           1       0.79      0.85      0.81        13

   micro avg       0.76      0.76      0.76        21
   macro avg       0.75      0.74      0.74        21
weighted avg       0.76      0.76      0.76        21

Train precision score: 0.7875
Test precision score: 0.7857142857142857


### QDA

In [18]:
scaler = True
qda_model = QDA.create_QDA_model() # Create
labels_x = ['pert_total_nouns', 'n_words',  'title_sentiment']
res = do_test(qda_model, df_train, df_test,labels_x, 'fake', scaler, 'QDA')

For labels: pert_total_nouns, n_words, title_sentiment
Confusion matrix:
[[ 6  2]
 [ 2 11]]
REPORT:
              precision    recall  f1-score   support

           0       0.75      0.75      0.75         8
           1       0.85      0.85      0.85        13

   micro avg       0.81      0.81      0.81        21
   macro avg       0.80      0.80      0.80        21
weighted avg       0.81      0.81      0.81        21

Train precision score: 0.75
Test precision score: 0.8461538461538461


In [19]:
labels_x = ['pert_total_nouns','n_words', 'title_sentiment', 'title_n_words', 'mean_words_per_sentence']
res = do_test(qda_model, df_train, df_test,labels_x, 'fake', scaler, 'QDA')

For labels: pert_total_nouns, n_words, title_sentiment, title_n_words, mean_words_per_sentence
Confusion matrix:
[[ 4  4]
 [ 1 12]]
REPORT:
              precision    recall  f1-score   support

           0       0.80      0.50      0.62         8
           1       0.75      0.92      0.83        13

   micro avg       0.76      0.76      0.76        21
   macro avg       0.78      0.71      0.72        21
weighted avg       0.77      0.76      0.75        21

Train precision score: 0.775
Test precision score: 0.75
